<script>
    document.addEventListener("DOMContentLoaded", function () {
        var recentlyViewedProducts = localStorage.getItem("recently_viewed_product");

        if (recentlyViewedProducts) {
            var date = new Date();
            date.setTime(date.getTime()+(10*60*1000)); // cookie lifetime 10 minutes
    
            document.cookie = "kiliba_recent=" + encodeURIComponent(recentlyViewedProducts) + "; expires=" + date.toUTCString() + "; path=/";
        }
    });
</script>